// <auto-generated />
namespace SOSWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Testing_birthday_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Testing_birthday_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201802251657156_Testing_birthday_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
