// <auto-generated />
namespace SOSWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Test_IsNonClinicalFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test_IsNonClinicalFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201802252326161_Test_IsNonClinicalFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
